	db _EOL
	
	db _CHEQUERBOARD, _CHEQUERBOARD, _CHEQUERBOARD
	db _A, _B, _C, _D, _E, _F, _G, _H, _I, _J, _K, _L, _M
	db _N, _O, _P, _Q, _R, _S, _T, _U, _V, _W, _X, _Y, _Z
	db _CHEQUERBOARD, _CHEQUERBOARD, _CHEQUERBOARD
	db _EOL

	db _CHEQUERBOARD, _CHEQUERBOARD
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _CHEQUERBOARD, _CHEQUERBOARD
	db _EOL

	db _0, _1
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _0, _1
	db _EOL

	db _0, _2
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _0, _2
	db _EOL

	db _0, _3
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _0, _3
	db _EOL

	db _0, _4
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _0, _4
	db _EOL

	db _0, _5
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _0, _5
	db _EOL

	db _0, _6
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _0, _6
	db _EOL

	db _0, _7
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _0, _7
	db _EOL

	db _0, _8
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _0, _8
	db _EOL

	db _0, _9
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _0, _9
	db _EOL

	db _1, _0
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _1, _0
	db _EOL

	db _1, _1
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _1, _1
	db _EOL

	db _1, _2
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _1, _2
	db _EOL

	db _1, _3
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _1, _3
	db _EOL

	db _1, _4
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _1, _4
	db _EOL

	db _1, _5
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _1, _5
	db _EOL

	db _1, _6
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _1, _6
	db _EOL

	db _CHEQUERBOARD, _CHEQUERBOARD
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _INVSPACE, _INVSPACE, _INVSPACE, _INVSPACE
	db _CHEQUERBOARD, _CHEQUERBOARD
	db _EOL

	db _CHEQUERBOARD, _CHEQUERBOARD, _CHEQUERBOARD
	db _A, _B, _C, _D, _E, _F, _G, _H, _I, _J, _K, _L, _M
	db _N, _O, _P, _Q, _R, _S, _T, _U, _V, _W, _X, _Y, _Z
	db _CHEQUERBOARD, _CHEQUERBOARD, _CHEQUERBOARD
	db _EOL

	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _EOL
	
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _EOL
	
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _EOL
	
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _SPACE, _SPACE, _SPACE, _SPACE
	db _EOL

	
